import type { Metadata } from "next";
import { Poppins as Fira_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Fira_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fira",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative flex justify-center items-center">
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
